SparkAutoRazor/Pages/Cars/Create.cshtml.cs
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using SparkAutoRazor.Data;
using SparkAutoRazor.Model;

namespace SparkAutoRazor.Pages.Cars
{
    [Authorize]
    public class CreateModel : PageModel
    {
        private readonly ApplicationDbContext _dbContext;

        public CreateModel(ApplicationDbContext dbContext)
        {
            _dbContext = dbContext;
        }

        [BindProperty]
        public Car Car { get; set; }


        [TempData] public string StatusMessage { get; set; }

        public IActionResult OnGet(string userId = null)
        {
            Car = new Car();
            if (string.IsNullOrEmpty(userId))
            {
                var claimsIdentity = (ClaimsIdentity)User.Identity;
                var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);

                userId = claim.Value;

            }

            Car.UserId = userId;
            return Page();
        }

        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            _dbContext.Cars.Add(Car);
            await _dbContext.SaveChangesAsync();

            StatusMessage = "New Car has been created successfully...";

            return RedirectToPage("Index", new { userId = Car.UserId });
        }
    }
}

SparkAutoRazor/Pages/ServiceTypes/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using SparkAutoRazor.Data;
using SparkAutoRazor.Model;
using SparkAutoRazor.Utility;

namespace SparkAutoRazor.Pages.ServiceTypes
{
    [Authorize(Roles = StaticDetails.AdminEndUser)]
    public class CreateModel : PageModel
    {
        private readonly ApplicationDbContext _dbContext;

        public CreateModel(ApplicationDbContext dbContext)
        {
            _dbContext = dbContext;
        }

        [BindProperty]
        public ServiceType ServiceType { get; set; }

        public IActionResult OnGet()
        {
            return Page();
        }

        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            _dbContext.ServiceTypes.Add(ServiceType);
            await _dbContext.SaveChangesAsync();

            return RedirectToPage("Index");
        }
    }
}

SparkAutoRazor/Pages/ServiceTypes/Details.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using SparkAutoRazor.Data;
using SparkAutoRazor.Model;
using SparkAutoRazor.Utility;

namespace SparkAutoRazor.Pages.ServiceTypes
{
    [Authorize(Roles = StaticDetails.AdminEndUser)]
    public class DetailsModel : PageModel
    {
        private readonly ApplicationDbContext _dbContext;

        public DetailsModel(ApplicationDbContext dbContext)
        {
            _dbContext = dbContext;
        }
        public async Task<IActionResult> OnGet(int id)
        {
            ServiceType = await _dbContext.ServiceTypes.FirstOrDefaultAsync(s => s.Id == id);
            return Page();
        }

        [BindProperty]
        public ServiceType ServiceType { get; set; }
    }
}

SparkAutoRazor/Pages/Services/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using SparkAutoRazor.Data;
using SparkAutoRazor.Model;
using SparkAutoRazor.Model.ViewModel;
using SparkAutoRazor.Utility;

namespace SparkAutoRazor.Pages.Services
{
    [Authorize(Roles = StaticDetails.AdminEndUser)]
    public class CreateModel : PageModel
    {
        private readonly ApplicationDbContext _dbContext;

        public CreateModel(ApplicationDbContext dbContext)
        {
            _dbContext = dbContext;
        }

        [BindProperty]
        public CarServiceViewModel CarServiceVM { get; set; }

        public async Task<IActionResult> OnGet(int carId)
        {
            CarServiceVM = new CarServiceViewModel
            {
                Car = await _dbContext.Cars.Include(c => c.ApplicationUser).FirstOrDefaultAsync(c => c.Id == carId),
                ServiceHeader = new ServiceHeader()
            };

            List<string> listServiceTypeInShoppingCart = await _dbContext.ServiceShoppingCarts
                                                            .Include(s => s.ServiceType)
                                                            .Where(c => c.CarId == carId)
                                                            .Select(c => c.ServiceType.Name)
                                                            .ToListAsync();


            IQueryable<ServiceType> lstService = from s in _dbContext.ServiceTypes
                                                 where !listServiceTypeInShoppingCart.Contains(s.Name)
                                                 select s;
            CarServiceVM.ServiceTypesList = await lstService.ToListAsync();

            CarServiceVM.ServiceShoppingCart = await _dbContext.ServiceShoppingCarts
                .Include(s => s.ServiceType)
                .Where(c => c.CarId == carId)
                .ToListAsync();

            CarServiceVM.ServiceHeader.TotalPrice = 0;

            foreach (var item in CarServiceVM.ServiceShoppingCart)
            {
                CarServiceVM.ServiceHeader.TotalPrice += item.ServiceType.Price;

            }

            return Page();
        }


        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            CarServiceVM.ServiceHeader.DateAdded = DateTime.Now;
            CarServiceVM.ServiceShoppingCart = _dbContext.ServiceShoppingCarts
                .Include(c => c.ServiceType)
                .Where(c => c.CarId == CarServiceVM.Car.Id)
                .ToList();


            foreach (var item in CarServiceVM.ServiceShoppingCart)
            {

                CarServiceVM.ServiceHeader.TotalPrice += item.ServiceType.Price;
            }

            CarServiceVM.ServiceHeader.CarId = CarServiceVM.Car.Id;

            _dbContext.ServiceHeaders.Add(CarServiceVM.ServiceHeader);
            await _dbContext.SaveChangesAsync();

            foreach (var detail in CarServiceVM.ServiceShoppingCart)
            {
                var serviceDetails = new ServiceDetails
                {
                    ServiceHeaderId = CarServiceVM.ServiceHeader.Id,
                    ServiceName = detail.ServiceType.Name,
                    ServicePrice = detail.ServiceType.Price,
                    ServiceTypeId = detail.ServiceTypeId
                };
                _dbContext.ServiceDetailses.Add(serviceDetails);
            }
            _dbContext.ServiceShoppingCarts.RemoveRange(CarServiceVM.ServiceShoppingCart);

            await _dbContext.SaveChangesAsync();


            return RedirectToPage("../Cars/Index", new { userId = CarServiceVM.Car.UserId });


        }

        public async Task<IActionResult> OnPostAddToCart()
        {
            ServiceShoppingCart objServiceCart = new ServiceShoppingCart
            {
                CarId = CarServiceVM.Car.Id,
                ServiceTypeId = CarServiceVM.ServiceDetails.ServiceTypeId,
            };

            _dbContext.ServiceShoppingCarts.Add(objServiceCart);
            await _dbContext.SaveChangesAsync();

            return RedirectToPage("Create", new { carId = CarServiceVM.Car.Id });
        }

        public async Task<IActionResult> OnPostRemoveFromCart(int serviceTypeId)
        {
            ServiceShoppingCart objServiceCartDb =
                await _dbContext.ServiceShoppingCarts.FirstOrDefaultAsync(u => u.ServiceTypeId == serviceTypeId &&
                                                                               u.CarId == CarServiceVM.Car.Id);


            _dbContext.ServiceShoppingCarts.Remove(objServiceCartDb);
            await _dbContext.SaveChangesAsync();

            return RedirectToPage("Create", new { carId = CarServiceVM.Car.Id });
        }
    }
}

SparkAutoRazor/Pages/Services/Details.cshtml.cs
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using SparkAutoRazor.Data;
using SparkAutoRazor.Model;

namespace SparkAutoRazor.Pages.Services
{
    [Authorize]
    public class DetailsModel : PageModel
    {
        private readonly ApplicationDbContext _dbContext;

        public DetailsModel(ApplicationDbContext dbContext)
        {
            _dbContext = dbContext;
        }

        public ServiceHeader ServiceHeader { get; set; }

        public List<ServiceDetails> ServiceDetailses { get; set; }
        public void OnGet(int serviceId)
        {
            ServiceHeader = _dbContext.ServiceHeaders
                .Include(c => c.Car)
                .Include(c => c.Car.ApplicationUser)
                .FirstOrDefault(s => s.Id == serviceId);

            ServiceDetailses = _dbContext.ServiceDetailses.Where(s => s.ServiceHeaderId == serviceId).ToList();

        }
    }
}

SparkAutoRazor/Pages/Services/History.cshtml.cs
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using SparkAutoRazor.Data;
using SparkAutoRazor.Model;

namespace SparkAutoRazor.Pages.Services
{
    [Authorize]
    public class HistoryModel : PageModel
    {
        private readonly ApplicationDbContext _dbContext;

        public HistoryModel(ApplicationDbContext dbContext)
        {
            _dbContext = dbContext;
        }

        [BindProperty] public List<ServiceHeader> ServiceHeaders { get; set; }

        public string UserId { get; set; }
        public async Task<IActionResult> OnGet(int carId)
        {

            ServiceHeaders = await _dbContext.ServiceHeaders
                .Include(s => s.Car)
                .Include(s=>s.Car.ApplicationUser)
                .Where(c=>c.CarId == carId)
                .ToListAsync();
            UserId = (await _dbContext.Cars.Where(u => u.Id == carId).ToListAsync()).FirstOrDefault().UserId;


            return Page(); 
        }
    }
}

SparkAutoRazor/Pages/Services/Create.cshtml
@page
@using SparkAutoRazor.Utility
@model SparkAutoRazor.Pages.Services.CreateModel
@{
    ViewData["Title"] = "Create";
    Layout = "~/Pages/Shared/_Layout.cshtml";
}

<div class="container pt-4 pb-2 row">
    <div class="col-6">
        <h2 class="text-info py-2">Create new service</h2>
    </div>
    <div class="col-3 offset-3 text-right py-2">
        <a asp-page="../Cars/Index" asp-route-userId="@Model.CarServiceVM.Car.UserId"
           class="btn btn-outline-success form-control">Back to list</a>
    </div>
</div>

<div class="container backgroundWhite">
    <div class="card">
        <div class="card-header bg-dark text-light ml-0 row container">
            <div class="col-1 text-center pt-3 text-white-50">
                <i class="far fa-user fa-2x"></i>
            </div>
            <div class="col-5">
                <label class="text-info">@Model.CarServiceVM.Car.ApplicationUser.Name</label><br />
                <label class="text-info">@Model.CarServiceVM.Car.ApplicationUser.Email / @Model.CarServiceVM.Car.ApplicationUser.PhoneNumber</label><br />
            </div>
            <div class="col-5 text-right">
                <label class="text-info">@Model.CarServiceVM.Car.Make @Model.CarServiceVM.Car.Model @Model.CarServiceVM.Car.Style</label><br />
                <label class="text-info">@Model.CarServiceVM.Car.Year</label><br />

            </div>
            <div class="col-1 text-center pt-3 text-white-50">
                <i class="fas fa-car fa-2x"></i>
            </div>
        </div>
        <div class="card-body">
            <form method="post" style="width: 100%">
                <div class="container">
                    <input type="hidden" asp-for="CarServiceVM.Car.Make" />
                    <input type="hidden" asp-for="CarServiceVM.Car.Model" />
                    <input type="hidden" asp-for="CarServiceVM.Car.VIN" />
                    <input type="hidden" asp-for="CarServiceVM.Car.UserId" />
                    <input type="hidden" asp-for="CarServiceVM.Car.Id" />

                    <div class="border rounded p-2">
                        <div class="row">
                            <div class="col-3">
                                <h4 class="text-info pl-3 pt-2 pb-1">Add Service</h4>
                            </div>
                            <div class="col-9 pb-1 pt-2">
                                <div class="row">
                                    <div class="col-8">
                                        <select asp-for="CarServiceVM.ServiceDetails.ServiceTypeId"
                                                asp-items="@(new SelectList(Model.CarServiceVM.ServiceTypesList, "Id", "Name"))"
                                                class="form-control"></select>
                                    </div>
                                    <div class="col-4">
                                        <button type="submit" asp-page-handler="AddToCart" class="form-control btn btn-primary">
                                            Add
                                        </button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                    <br />

                    <div class="border container rounded p-2">
                        <h3 class="text-info pb-2">Service summary</h3>
                        @if (!Model.CarServiceVM.ServiceShoppingCart.Any())
                        {
                            <p>
                                No service has been added yet. Please add a service to be performed.
                            </p>
                        }
                        else
                        {
                            <div class="row mt-3">
                                <div class="col-7">
                                    <table class="table table-striped border">
                                        <tr class="table-secondary">
                                            <th>
                                                @Html.DisplayNameFor(m => Model.CarServiceVM.ServiceTypesList.FirstOrDefault().Name)
                                            </th>
                                            <th>
                                                @Html.DisplayNameFor(m => Model.CarServiceVM.ServiceTypesList.FirstOrDefault().Price)
                                            </th>
                                            <th>

                                            </th>
                                        </tr>
                                        @foreach (var item in Model.CarServiceVM.ServiceShoppingCart)
                                        {
                                            <tr>
                                                <td>
                                                    @Html.DisplayFor(m => item.ServiceType.Name)
                                                </td>
                                                <td>
                                                    @Html.DisplayFor(m => item.ServiceType.Price)
                                                </td>
                                                <td>
                                                    <button type="submit"
                                                            asp-page-handler="RemoveFromCart"
                                                            asp-route-serviceTypeId="@item.ServiceTypeId"
                                                            class="btn btn-danger form-control">
                                                        <i class="far fa-trash-alt"></i>
                                                    </button>
                                                </td>
                                            </tr>
                                        }
                                        <tr style="background-color: #e2fee2">
                                            <td colspan="1">
                                                <h6 class="text-success">Total price :</h6>
                                            </td>
                                            <td colspan="2">
                                                <h6 class="text-success">$@Model.CarServiceVM.ServiceHeader.TotalPrice</h6>
                                            </td>
                                        </tr>
                                    </table>
                                </div>
                                <div class="col-5 px-4 pb-2">
                                    <div class="row">
                                        <div class="col-3">
                                            <label asp-for="CarServiceVM.ServiceHeader.Miles" class="form-control" style="border:none"></label>
                                        </div>
                                        <div class="col-9">
                                            <input asp-for="CarServiceVM.ServiceHeader.Miles" id="txtMiles" class="form-control" />
                                        </div>
                                    </div>
                                    <div class="row py-2">
                                        <div class="col-12">
                                            <textarea placeholder="Comments..." asp-for="CarServiceVM.ServiceHeader.Details" class="form-control" style="height: 100px"></textarea>
                                        </div>
                                    </div>
                                    <div class="row p-0">
                                        <div class="col-12">
                                            <button class="btn btn-success form-control" onclick="return validateInput()">Service Complited</button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        }
                    </div>

                </div>
            </form>
        </div>
    </div>
</div>


@section Scripts
{
    <partial name="Shared/_ValidationScriptsPartial"/>

    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
    
    <script type="text/javascript">
        function validateInput() {
            var miles = document.getElementById("txtMiles").value;

            if (miles < 1) {
                swal("Error!", "miles can't be empty or 0", "error");
                return false;
            } 
        }
    </script>
}

SparkAutoRazor/Pages/Services/Details.cshtml
@page
@model SparkAutoRazor.Pages.Services.DetailsModel
@{
    ViewData["Title"] = "Details";
    Layout = "~/Pages/Shared/_Layout.cshtml";
}


<div class="container pt-4 pb-2 row">
    <div class="col-6">
        <h2 class="text-info py-2">Service Details</h2>
    </div>
    <div class="col-3 offset-3 text-right py-2">
        <a asp-page="/Services/History" asp-route-userId="@Model.ServiceHeader.CarId"
           class="btn btn-outline-success form-control">Back to list</a>
    </div>
</div>

<div class="container backgroundWhite">
    <div class="card">
        <div class="card-header bg-dark text-light ml-0 row container">
            <div class="col-1 text-center pt-3 text-white-50">
                <i class="far fa-user fa-2x"></i>
            </div>
            <div class="col-5">
                <label class="text-info">@Model.ServiceHeader.Car.ApplicationUser.Name</label><br />
                <label class="text-info">@Model.ServiceHeader.Car.ApplicationUser.Email / @Model.ServiceHeader.Car.ApplicationUser.PhoneNumber</label><br />
            </div>
            <div class="col-5 text-right">
                <label class="text-info">@Model.ServiceHeader.Car.Make @Model.ServiceHeader.Car.Model @Model.ServiceHeader.Car.Style</label><br />
                <label class="text-info">@Model.ServiceHeader.Car.Year</label><br />

            </div>
            <div class="col-1 text-center pt-3 text-white-50">
                <i class="fas fa-car fa-2x"></i>
            </div>
        </div>
        <div class="card-body">
            <div class="row pt-3">


                <div class="col-7">

                    <table class="table table-striped border">
                        <tr class="table-secondary">
                            <th>
                                @Html.DisplayNameFor(m => Model.ServiceDetailses[0].ServiceName)
                            </th>
                            <th>
                                @Html.DisplayNameFor(m => Model.ServiceDetailses[0].ServiceName)
                            </th>
                        </tr>
                        @foreach (var item in Model.ServiceDetailses)
                        {
                            <tr>
                                <td>
                                    @Html.DisplayFor(m => item.ServiceName)
                                </td>
                                <td>
                                    @Html.DisplayFor(m => item.ServicePrice)
                                </td>
                            </tr>
                        }
                        <tr style="background-color: #e2fee2">
                            <td colspan="1">
                                <h6 class="text-success">Total price :</h6>
                            </td>
                            <td colspan="1">
                                <h6 class="text-success">$@Model.ServiceHeader.TotalPrice</h6>
                            </td>
                        </tr>
                    </table>
                </div>
                <div class="col-5 px-4 pb-2">
                    <div class="row">
                        <div class="col-3">
                            <label asp-for="ServiceHeader.Miles" readonly class="form-control" style="border:none"></label>
                        </div>
                        <div class="col-9">
                            <input asp-for="ServiceHeader.Miles" readonly id="txtMiles" class="form-control" />
                        </div>
                    </div>
                    <div class="row py-2">
                        <div class="col-12">
                            <textarea placeholder="Comments..." asp-for="ServiceHeader.Details" class="form-control" style="height: 100px"></textarea>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

SparkAutoRazor/Pages/Services/History.cshtml
@page
@model SparkAutoRazor.Pages.Services.HistoryModel
@{
    ViewData["Title"] = "History";
    Layout = "~/Pages/Shared/_Layout.cshtml";
}


<div class="container pt-4 pb-2 row">
    <div class="col-6">
        <h2 class="text-info py-2">Service History</h2>
    </div>
    <div class="col-3 offset-3 text-right py-2">
        <a asp-page="../Cars/Index" asp-route-userId="@Model.UserId"
           class="btn btn-outline-success form-control">Back to list</a>
    </div>
</div>

@if (!Model.ServiceHeaders.Any())
{
    <div class="backgroundWhite">
        <p>No Service record found...</p>
    </div>
}
else
{

    <div class="container backgroundWhite">
        <div class="card">
            <div class="card-header bg-dark text-light ml-0 row container">
                <div class="col-1 text-center pt-3 text-white-50">
                    <i class="far fa-user fa-2x"></i>
                </div>
                <div class="col-5">
                    <label class="text-info">@Model.ServiceHeaders[0].Car.ApplicationUser.Name</label><br />
                    <label class="text-info">@Model.ServiceHeaders[0].Car.ApplicationUser.Email / @Model.ServiceHeaders[0].Car.ApplicationUser.PhoneNumber</label><br />
                </div>
                <div class="col-5 text-right">
                    <label class="text-info">@Model.ServiceHeaders[0].Car.Make @Model.ServiceHeaders[0].Car.Model @Model.ServiceHeaders[0].Car.Style</label><br />
                    <label class="text-info">@Model.ServiceHeaders[0].Car.Year</label><br />

                </div>
                <div class="col-1 text-center pt-3 text-white-50">
                    <i class="fas fa-car fa-2x"></i>
                </div>
            </div>
            <div class="card-body">

                <table class="table table-striped border">
                    <tr class="table-secondary">
                        <th>
                            @Html.DisplayNameFor(m => Model.ServiceHeaders[0].Miles)
                        </th>
                        <th>
                            @Html.DisplayNameFor(m => Model.ServiceHeaders[0].TotalPrice)
                        </th>
                        <th>
                            @Html.DisplayNameFor(m => Model.ServiceHeaders[0].Details)
                        </th>
                        <th>
                            @Html.DisplayNameFor(m => Model.ServiceHeaders[0].DateAdded)
                        </th>
                        <th>

                        </th>
                    </tr>
                    @foreach (var item in Model.ServiceHeaders)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(m => item.Miles)
                            </td>
                            <td>
                                @Html.DisplayFor(m => item.TotalPrice)
                            </td>
                            <td>
                                @Html.DisplayFor(m => item.Details)
                            </td>
                            <td>
                                @Html.DisplayFor(m => item.DateAdded)
                            </td>
                            <td>
                                <a asp-page="Details" class="btn btn-info form-control" asp-route-serviceId="@item.Id">
                                    <i class="fas fa-list-alt"></i>
                                </a> 
                            </td>
                        </tr>
                    } 
                </table> 
            </div>
        </div>
    </div>

}